[build]
  command = "ng build --configuration production"
  publish = "dist/tcg3d-shop/browser"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Redirigir todo a index.html para Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
